language: python
sudo: false

python:
  - 2.7

env:
  global:
    - DISPLAY=:99.0
  matrix:
  - TOXENV=flake8
  - TOXENV=docs
  - TOXENV=assets
  - TOXENV=es
  - TOXENV=addons
  - TOXENV=devhub
  - TOXENV=editors
  - TOXENV=amo
  - TOXENV=users
  - TOXENV=main
  - TOXENV=ui-tests

cache:
  pip: true
  directories:
    - node_modules

services:
  - memcached
  - elasticsearch

addons:
  apt:
    sources:
      - elasticsearch-5.x
    packages:
      - swig
      - oracle-java8-set-default
      - elasticsearch
  firefox: latest

install:
  - nvm current
  - nvm deactivate
  - nvm install 4
  - nvm use 4
  - pip install --upgrade pip wheel setuptools tox==1.8.1

before_script:
  - mysql -e 'create database olympia;'
  - node --version
  - java -version
  - curl -v http://localhost:9200/
  - |
      if [[ $TOXENV == "ui-tests" ]]; then
        wget -O /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
        mkdir $HOME/geckodriver && tar xvf /tmp/geckodriver.tar.gz -C $HOME/geckodriver
        export PATH=$HOME/geckodriver:$PATH
        firefox --version
        geckodriver --version
        sh -e /etc/init.d/xvfb start
        sleep 10
      fi

script:
  - RUNNING_IN_CI=True tox -v

notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always

git:
  depth: 1
